## Numpy의 자료형
* Numpy의 배열 즉, 'narray' 클래스는 원소(element)가 모두 같은 자료형이어야 함
* 'np.array'로 배열을 만들 때 자료형을 안 주면 자동으로 지정. 명시적으로 적용하고 싶을때 'dtype' 인수
* 만들어진 배열의 자료형을 알고 싶으면 'dtype' 속성

In [4]:
import numpy as np

In [5]:
x = np.array([1,2,3]) # int 정수 ->추론 -> int array
x

array([1, 2, 3])

In [7]:
x.dtype # 64? 32? 크기

dtype('int64')

In [8]:
x = np.array([1,2,3.0])
x.dtype # 정수(int) < 실수(float) < ... < Object

dtype('float64')

In [9]:
x = np.array([1,2,3], dtype='f')
x.dtype 

dtype('float32')

* `dtype` 인수
    * dtype 접두사로 시작하는 문자열
    * 접두사 뒤 오는 숫자 = 바이트 수 혹은 글자 수
    * 숫자 생략 시 운영체제에 따라 알맞은 크기 지정

|dtype 접두사|설명|사용 예|
|-|-|-|
|`b`|불리언|`b` (참 혹은 거짓)|
|`i`|정수|`i8` (64비트)|
|`u`|부호 없는 정수|`u8` (64비트)|
|`f`|부동소수점|`f8` (64비트)|
|`c`|복소 부동소수점|`c16` (128비트)|
|`O`|객체|`0` (객체에 대한 포인터)|
|`S`|바이트 문자열|`S24` (24 글자)|
|`U`|유니코드 문자열|`U24` (24 유니코드 글자)|

In [10]:
x= np.array([1,2,3], dtype='f') # float - > 숫자가 없으니까
x.dtype

dtype('float32')

In [11]:
x[0] + x[1] # 1+2 = 3

3.0

In [12]:
x = np.array([1,2,3],dtype='U')
x.dtype

dtype('<U1')

In [13]:
x[0] + x[1] # 문자 상태니까 +는 연결을 한다. # dtype으로 확인을 해야한다.

'12'

## inf와 NaN 
* 무한대를 표현하기 위한 `np.inf`(infinity)라는 값이 있음
* 정의할 수 없는 숫자: `np.nan`(not a number)

In [14]:
np.array([0,1,-1,0]) / np.array([1,0,0,0]) # 결과 0,  inf, -inf,  nan(0끼리 나눌 수 없음)

<ipython-input-14-720e9e2d83ea>:1: RuntimeWarning: divide by zero encountered in true_divide
  np.array([0,1,-1,0]) / np.array([1,0,0,0])
<ipython-input-14-720e9e2d83ea>:1: RuntimeWarning: invalid value encountered in true_divide
  np.array([0,1,-1,0]) / np.array([1,0,0,0])


array([  0.,  inf, -inf,  nan])

In [15]:
np.log(0)

<ipython-input-15-f6e7c0610b57>:1: RuntimeWarning: divide by zero encountered in log
  np.log(0)


-inf

## 배열 생성

In [18]:
#@title np.zeros : 크기가 정해져 있고, 모든 값이 0인 배열을 생성
a = np.zeros(5) # 배열을 선언하는데 0으로 채운 것!
a

array([0., 0., 0., 0., 0.])

In [22]:
# 튜플을 넣으면 해당 크기의 0으로 채워진 다차원 배열을 생성
b = np.zeros((2,3))
b

array([[0., 0., 0.],
       [0., 0., 0.]])

In [23]:
b.shape

(2, 3)

In [20]:
b.dtype

dtype('float64')

In [21]:
# dtype 인수 명시 할 경우 해당 자료형 원소 타입 부여
c= np.zeros((5,2), dtype='i')
c

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]], dtype=int32)

In [24]:
# zeros 숫자 -> 모든 원소의 문자열 크기만 갖다면 문자열 배열
# 만약 더 큰 크기의 문자열을 할당하면 잘림
d = np.zeros(5, dtype='U4')

In [26]:
d[0] = 'abc'
d[1] = 'abcd'
d[2] = 'ABCDE' #E가 짤림
d

array(['abc', 'abcd', 'ABCD', '', ''], dtype='<U4')

## ones: 1로 초기화된 배열 생성

In [27]:
e = np.ones((2,3,4), dtype='i8')
e

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [29]:
f = np.ones_like(b,dtype='f') #1으로 
f, f.shape

(array([[1., 1., 1.],
        [1., 1., 1.]], dtype=float32), (2, 3))

In [31]:
#@title np.empty
# * 시간이 절약, 메모리 절약
# * 초기화를 하지 않는다 -> 덮어씌우지 않음
# * 자리만 잡고 테이블은 안치움

g = np.empty((4,3)) 
g

array([[1.84862448e-316, 2.47032823e-322, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 1.31370903e-076],
       [4.51235098e-090, 3.99761409e+175, 3.63421710e+174],
       [8.83077831e+169, 3.99910963e+252, 1.46030983e-319]])

In [33]:
g.shape, g.dtype

((4, 3), dtype('float64'))

## np.arange: 특정 규칙에 따라 증가하는 수열 ->  배열 range


In [34]:
np.arange(3,21,2) # 시작(포함), 끝(끝-1까지), 단계

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19])

## np.linspace(linear)
* 선현구간을 지정한 구간의 수만큼 분활

In [36]:
np.linspace(0,100,5) # 시작(포함), 끝(끝-1까지), 단계

array([  0.,  25.,  50.,  75., 100.])

## np.logspace(log)
* 로그 구간을 지정

In [37]:
np.logspace(0.1,1,10)

array([ 1.25892541,  1.58489319,  1.99526231,  2.51188643,  3.16227766,
        3.98107171,  5.01187234,  6.30957344,  7.94328235, 10.        ])

## 전치연산(transpose)
* 2차원 배열에서 행과 열을 바꾸는 작업
* 배열의 T 속성

In [38]:
A = np.array([[1,2,3],[4,5,6]])
A, A.shape # (2, 3)

(array([[1, 2, 3],
        [4, 5, 6]]), (2, 3))

In [40]:
A.T, A.shape # (2, 3)

(array([[1, 4],
        [2, 5],
        [3, 6]]), (2, 3))

## 배열의 크기 변형(`reshape`)

In [41]:
a = np.arange(12) # 0 - 11까지
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [42]:
# (12) -> (3,4)
b = a.reshape(3,4) # 배열의 모양을 바꿔줌 1차원 배열을 2차원배열로 변형
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [44]:
# -1 : 행의 개수를 정하면 알아서 열의 개수가 결정됨 -> 다른 값들을 통해서 계산된 값을 채워줌
a.reshape(3,-1) #12 ->3으로 나누니 남은 수가 4인데 대신 -1로 표시 가능, 행, 열 둘 중에 하나를 -1로 가능

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [45]:
#a.reshape(2,3,2)
a.reshape(-1,3,2) # 하나는 -1로 바꿀 수 있다.

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

## 배열 평탄화(`flatten`,`ravel`)
* 다차원 배열을 1차원으로 변환

In [47]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [46]:
b.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [48]:
b.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

## 같은 배열에 대한 차원만 1차원 증가(`newaxis`)

In [49]:
x = np.arange(5) # 1차원 배열
x

array([0, 1, 2, 3, 4])

In [50]:
x[:, np.newaxis] # 차원을 추가함 # 1차원 배열이 2차원 배열로!

array([[0],
       [1],
       [2],
       [3],
       [4]])