<a href="https://colab.research.google.com/github/LeeJaeEun0/st1205/blob/main/221205_ch01_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

골든 서클 이론
* 목적, 목표 
* 어떤 방식, 도구를 사용할 것인가?
* 그래서 구체적으로 배우는데 뭘까?

인공지능: 인간의 지능을 흉내낸 컴퓨터 프로그램을 만드는 것<br>
 => 컴퓨터 프로그램이다. = 많은 계산, 많은 데이터를 처리할 수 있어야함<br>
 컴퓨터에 게 최적화된 방식으로 제공(숫자나 규치적으로 반복되는 것)<br>
 컴퓨터가 이해하기 좋게 데이터를 다듬는 과정(70%): 전처리<br>
 이해하기 좋다 = 0,1.... (우리가 이해할 수 없음)<br>
 반복되는 타입을 가진 나열된 데이터(배열)을 통해 컴퓨터가 이해하도록 => 넘파이가! <br>
 =>Numpy는 데이터를 다듬는 형태로 존재


## NumPy(넘파이 특징)
* 과학 계산을 위한 라이브러리
* 행렬/배열 처리 및 생산
* 난수 생성

# 배열
* 0개 이상의 데이터를 하나의 변수에 할당: 리스트(list)

In [ ]:
a = []
a.append('a')
a

['a']

* 리스트: 컴퓨터가 리스트를 싫어하는 이유(인간에 친화적이지만 컴퓨터에게는 어려움-처리하기 힘듬)
1. 길이가 가변적임 -> 메모리 문제(c/c++은 배열 길이를 먼저 선언)
2. 들어가는 타입이 다양함. -> int, str 등 여러 형을 같이 넣을 수 있다.<br>
  -> 예약 손님이 몇분인지, 메뉴도 모름
* 배열(컴퓨터에 친화적 - 처리하기 좋음)
1. 길이가 고정적임 (원소의 갯수를 바꿀 수가 없음)
2. 타입이 고정적인 (모든 원소의 타입이 같은 자료형이여함.)<br>
  -> 예약 손님이 10분인지, 샌드위치 10개<br>
  => 적은 메모리로 많은 데이터를 빠르게 처리할 수 있음

In [ ]:
# 파이썬에는 배열을 처리하는 자체 내장 패키지 x
# !pip install -> colab의 장점 : 웬만한 것 다 깔려 있음
import numpy as np
# colab에서 tab 누르면 자동완성
# colab 블록 실행: ctrl + enter
# 블록을 실행하고 추가 블록 생성: alt + enter

## 1차원 배열
* 축이 1개인 배열
* 리스트나 튜플처럼 한 줄로 이루어진 배열

In [ ]:
np.array([1,2,3])

array([1, 2, 3])

In [ ]:
np.array([1,2,3,'a']) # 다른 타입을 입력하는 경우

array(['1', '2', '3', 'a'], dtype='<U21')

In [ ]:
arr = np.array([i for i in range(10)])
type(arr) # ndarray -> numpy를 통해서 생성된 배열

numpy.ndarray

# ndarray 
* 배열 객체 타입(자료형)
* 리스트와 동일해 보이지만 차이가 많음

|자료형|특징|
|:-|:-|
|리스트(list)|각각의 원소가 다른 자료형이 될 수 있음|
|배열(array)|연속적인 메모리 배치를 가지기 때문에 모든 원소가 같은 자료형이어야 함<br>원소에 대한 접근과 반복문 실행이 빨라짐|

In [ ]:
import random # 임의의 수

def average_python(n):
  s = 0
  for i in range(n): #n번 반복문
    s += random.random() # 0~1 사이 수
  #s =??
  return s/n

In [ ]:
%time average_python(100000)

CPU times: user 21.4 ms, sys: 0 ns, total: 21.4 ms
Wall time: 25.8 ms


0.4990400423837849

In [ ]:
def abeverage_numpy(n):
  s = np.random.random(n)
  return s.mean() # 평균

In [ ]:
%time abeverage_numpy(100000)
%timeit abeverage_numpy(100000) #여러번 실행해서 비교 #넘파이가 더 빠름

CPU times: user 1.12 ms, sys: 2.93 ms, total: 4.05 ms
Wall time: 4.07 ms
1.05 ms ± 76.8 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


## 백터화 연산(vectorized operation)


In [ ]:
a = [1,2,3]
a

[1, 2, 3]

In [ ]:
# b리스트 = a 리스트 원소에 1씩 더해서
# a+1 - 오류 발생
# a*2 => 반복
# 백터를 통해서 원소에 일괄적으로 더하고 곱하고, 합치는 과정이 가능하다. -> 반복문을 사용하지 않고 만들기

* 배열객체(numpy.ndarray)는 **배열의 각 원소에 대한 반복 연산을 하나의 명령어**로 처리 = 백터화 연산

In [ ]:
data = [0,1,2,3,4,5,6,7,8,9] # for i in range(10)
data

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
# 리스트 속에 나열된 데이터를 모두 2배 처리
%%time
answer = []
for v in data:
  answer.append(v*2) # 2배로 곱하기 # 인덱스인 v를 2배 곱해서 넣는다는 의미(인수를 값을 증가시키는 것은 아니다)
answer

CPU times: user 22 µs, sys: 4 µs, total: 26 µs
Wall time: 31.7 µs


[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [ ]:
%%time
answer2 = [x * 2 for x in data]

CPU times: user 7 µs, sys: 1 µs, total: 8 µs
Wall time: 11.2 µs


In [ ]:
# 백터화 연산
%time
x = np.array(data)
x

CPU times: user 8 µs, sys: 0 ns, total: 8 µs
Wall time: 32.4 µs


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
%time x*2

CPU times: user 56 µs, sys: 0 ns, total: 56 µs
Wall time: 61.5 µs


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
data *2 # 리스트 * 2를 해서 리스트가 2번 출력

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
x/2, x+2,x^2, x%2 

(array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5]),
 array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11]),
 array([ 2,  3,  0,  1,  6,  7,  4,  5, 10, 11]),
 array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1]))

* 벡터화 연산은 사칙연산뿐만 아니라 비교 연산과 논리 연산을 포함한 모든 종류의 수학 연산에 대해 적용

In [ ]:
a = np.array([1,2,3])
b = np.array([10,20,30]) # alt + shift+ 위아래 방향키 => 복사
a,b # a와 b의 결과 출력

(array([1, 2, 3]), array([10, 20, 30]))

In [ ]:
2*a +b  #리스트와 차이점, 리스트는 2번 반복이었을 것 # 산술연산

array([12, 24, 36])

In [ ]:
a == 2, b>10 #비교 연산

(array([False,  True, False]), array([False,  True,  True]))

In [ ]:
(a ==2) & (b>10) # &: and 연산자 -> (같은 위치의 원소가)둘다 true인 경우

array([False,  True, False])

In [ ]:
(a ==2) | (b>10) # |: or 연산자 -> (같은 위치의 원소 중) 하나가 true인 경우

array([False,  True,  True])

## 2차원 배열
-> ndarray => n dimession array => 다차원배열의 자료구조를 지원
* 2차원 배열: 행렬(matrix)
* 가로줄: 행(row)
* 세로줄: 열(colum)
> 엑셀 스프레드시트와 같은 형태의 배열 -> pandas
list of list / 리스트의 리스트 -> 2차원 배열<br>
list of list of list / 리스트의 리스트의 리스트 -> 3차원 배열<br>




In [ ]:
m = np.array([
    [0,1,2],
    [3,4,5]
    ]) # 2 x 3 행렬 / m x n m : m 행의 개수, n 렬의 개수
m

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
# 행의 개수, 열의 개수
print("행의 개수: ",len(m)) # 행의 개수 - 가장 겉에 있는 리스트의 원소 개수
print("열의 개수: ",len(m[0])) # 열의 개수 - 가장 안에 있는 리스트의 원소 개수

행의 개수:  2
열의 개수:  3


✅ :을 누르면 설정가능
윈도우 + .=> 특수문자
# ✌ 연습문제1 
10 20 30 40 <br>
50 60 70 80

In [ ]:
#@title 연습문제1

# 리스트 업, 백터 연산 사용 등

# 1. 데이터 입력해서 넣기
li1 = [[10,20,30,40],[50,60,70,80]]
li1

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [ ]:
# 2,  np 이용
li2 = np.array([[10,20,30,40],[50,60,70,80]])
np.array(li2)

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [ ]:
# 3. 백터화 연산
li3 = np.array([[1,2,3,4],[5,6,7,8]])
np.array(li3) *10

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

## 3차원 배열

In [ ]:
t = np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]],[[11,12,13,14],[15,16,17,18],[19,20,21,22]]])
t # 2 x 3 x 4 배열 (3차원 배열)

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[11, 12, 13, 14],
        [15, 16, 17, 18],
        [19, 20, 21, 22]]])

In [ ]:
# 깊이 행 열
print("깊이: ",len(t)) 
print("행: ",len(t[0])) 
print("열: ",len(t[0][0])) # 이미지를 위해서 rgb 도 3개 필요!

깊이:  2
행:  3
열:  4


## 배열의 차원과 크기 알아내기
* ndim, shape **속성** 사용
- 메소드는 함수, () 사용
- 속성은 이름으로 사용가능
* ndim: 배열의 차원
* shape: 배열의 크기

In [ ]:
a.ndim, a.shape # 1차원 배열

(1, (3,))

In [ ]:
m.ndim, m.shape # 2차원 배열

(2, (2, 3))

In [ ]:
t.ndim, t.shape # 3차원 배열

(3, (2, 3, 4))

## 배열의 복사
* 얕은 복사(Shallow Copy)
* 깊은 복사(Deep Copy)

In [ ]:
1, '',0.1 # 원시 자료형 - 그대로 메모리에 기록된다 
# 변수
# 1. 상수와 대비되는 변수 - 상수는 변화가 없지만 변수는 값이 변할 수 있다.
# 2. 연결관계를 보여줌
a = [1,2,3]
a

[1, 2, 3]

In [ ]:
b = a
b

[1, 2, 3]

In [ ]:
a.append(4)
a

[1, 2, 3, 4]

In [ ]:
b # 얕은 복사 - a의 주소값을 받아서 4가 추가됨, 백업을 했다면 백업데이터도 변형이 된 것!!!

[1, 2, 3, 4]

In [ ]:
# 깊은 복사: 주소를 복사하는 것이 아니라 새로운 메모리에 값을 복사해서 연결관계 끊기
c = ['a','b','c']
c

['a', 'b', 'c']

In [ ]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [ ]:
arr2 = arr

In [ ]:
arr[0] = 10
arr2 # 아직 연결된 상태, 원소가 바뀜

array([10,  2,  3,  4])

In [ ]:
arr2.view() # 원본과 연결된 사본

array([10,  2,  3,  4])

In [ ]:
arr3 = arr.copy() # copy 함수 이용해서 관계를 끊음 # 함수는 ()있고 속성은 괄호 없음
arr2

array([10,  2,  3,  4])

In [ ]:
arr[0] = 100
arr3 # 원소가 바뀜 = 배열의 내용만 복사했기때문에 연결이 끊어짐

array([10,  2,  3,  4])

In [ ]:
arr3.view() # 원본과 연결이 되지 않은 사본

array([10,  2,  3,  4])

In [ ]:
print(arr2.base) # 배열의 데이터 소유 여부

None


In [ ]:
print(arr3.base) # 배열의 데이터 소유 여부

None


In [ ]:
arr = np.array([1,2,3,4,5])

x = arr.copy()
y = arr.view()

print(x.base) # 배열의 데이터 소유 여부 - 깊은 복사
print(y.base) # 배열의 데이터 소유 여부 - 얕은 복사

None
[1 2 3 4 5]


## 배열의 인덱싱


In [ ]:
a = [1,2,3,4,5]

In [ ]:
# a에서 3을 가져오고 싶다
a[2]

3

In [ ]:
a[-3]

3

## 일차원 배열 인덱싱
* 리스트의 인덱싱과 같은

In [ ]:
a = np.array([0,1,2,3,4])
a[2], a[-1]

(2, 4)

## 다차원 배열 인덱싱
* 콤마(comma, ',') 접근
* 콤마로 구분된 차원을 축(axis)이라고 함
* 그래프의 x축,y축

In [ ]:
b = np.array([[0,1,2],[3,4,5]])
b

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
b.shape

(2, 3)

In [ ]:
b[0,0] # 첫번째 행의 첫번째 열

0

In [ ]:
b[-1,-1] # 마지막 행의 마지막 열

5

## 배열의 슬라이싱


In [ ]:
x = [1,2,3,4]
x[1:3] # a:b => a는 포함,b제외(b-1까지 출력)

[2, 3]

In [ ]:
x[-3:-1] # [-4,-3,-2,-1]의 순서로 배치 되어있어서 -3과 -2 위치에 있는 [2,3] # 헷갈림 주의

[2, 3]

In [ ]:
x[:-1] # [-4,-3,-2,-1]의 순서로 배치 되어있어서 -4과 -2 위치에 있는 [1,2,3] # 헷갈림 주의

[1, 2, 3]

* 다차원 배열의 원소 중 2개 이상의(복수개)를 접근할 대 일반적인 파이썬 슬라이싱과 콤마를 같이 사용


In [ ]:
a = np.array([[0,1,2,3],[4,5,6,7]])
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [ ]:
a[0, :] # 첫번째 행 전체

array([0, 1, 2, 3])

In [ ]:
a[:,0] # 첫번째 열 전체

array([0, 4])

In [ ]:
a[1:,1:]  # 1행 1열부터 출력

array([[5, 6, 7]])

In [ ]:
1

array([[0, 1],
       [4, 5]])

## 🦕 연습문제2
```
m = np.array([[0,  1,  2,  3,  4],
              [5,  6,  7,  8,  9],
              [10, 11, 12, 13, 14]])
m
```
1. 값 7을 인덱싱
1. 값 14을 인덱싱
1. 배열 [6,7]을 슬라이싱
1. 배열 [7,12]을 슬라이싱
1. 배열 [[3,4],[8,9]]을 슬라이싱



In [ ]:
m = np.array([[0,  1,  2,  3,  4],
              [5,  6,  7,  8,  9],
              [10, 11, 12, 13, 14]])
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
m.shape # 3행 5열

(3, 5)

In [ ]:
# 1. 값 7을 인덱싱
m[1,2]
m[-2,-3]
m[1,-3]
m[-2,2]

7

In [ ]:
# 2. 값 14을 인덱싱
m[2,4]
m[-1,-1]
m[2,-1]
m[-1,4]

14

In [ ]:
#배열 [6,7]을 슬라이싱
m[1,1:3]
m[-2, 1:3]
m[1, -4:-2]
m[-2, -4:-2]

array([6, 7])

In [ ]:
#배열 [7,12]을 슬라이싱
m[1:3,2:3]
m[1,2] # 1행부터니까 1만 씀
m[-2:2]
m[-2:-3]
m[1,-3]

array([[ 7],
       [12]])

In [ ]:
#배열 [[3,4],[8,9]]을 슬라이싱
m[0:2,3:5]
m[:2,3:]
print(m[:-1,3:])
print(m[:2,-2:])
print(m[:-1,-2:])

array([[3, 4],
       [8, 9]])

## 배열 인덱싱 (배열을 넣어서 인덱싱 하겠다.)
arr[...] => 정수형의 값. 슬라이싱(:) 범위
대괄호(breacket, [])안에 인덱스 정보로 숫자나 슬라이스가 아니라 위치 정보를 나타내는 또 다른 'ndarray' 배역을 넣어서 특정 조건을 만족시키는 값만 조회
* 1) 불(Bool)리언 값으로 되어 있는 배열
*2) 정수 인덱스 배열


In [ ]:
# 벡터화 연산 -> 비교, 논리 연산
# 불리언 배열 인덱싱
# - 인덱스 배열의 원소가 True, False 두 값으로만 구성되며 배열의 크가 원래 ndarray 객체의 크기와 같을때 
#벡터화 연산 -> 비교, 논리 연산

In [ ]:
a = np.array([0,1,2,3,4,5,6,7,8,9]) # 배열 -> 짝수 원소만 골라내고 싶다
idx = np.array([True, False,True, False,True, False,True, False,True, False]) # true, false로 채운 배열
a[idx] # true인 결과나 # 괄호안에 배열을 넣을 수 있음 - true 인 결과만 출력

array([0, 2, 4, 6, 8])

In [ ]:
# 벡터화 연산 -> 논리연산, 비교 연산
a % 2 # 2의 배수는 나머지가 0일때 짝수
a % 2 == 0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [ ]:
a[a%2==0] # 조건문으로 계산해서 (벡터화 연산) 원래 배열에 인덱스를 넣어주면, 필터링이 된다 - 걸러내준다, 특정조건에 맞는 내용 가져오기

array([0, 2, 4, 6, 8])

In [ ]:
a[a%3==0] # a를 3으로 나눈 나머지가 0인 결과가 True인 원소만 출력

array([0, 3, 6, 9])

In [ ]:
a[a%3!=0] # a를 3으로 나눈 나머지가 0과 같지 않은 결과가 True인 원소만 출력

array([1, 2, 4, 5, 7, 8])

## 정수 배열 인덱싱
* 원래 배열의 인덱스 -> 정수값의 라벨링(0~)
* 특정 정수들의 인덱스 배열을 넣으면, 해당 정수에 대응하는 값을 찾아서 표현해줌

In [ ]:
a = np.array([1,2,3,4,5,6,7,8,9]) * 11
a

array([11, 22, 33, 44, 55, 66, 77, 88, 99])

In [ ]:
idx = np.array([0,2,4,6,8])
a[idx] #특정한 위치에 해당하는 값을 호출

array([11, 33, 55, 77, 99])

In [ ]:
idx2 =np.array([0,0,0,0,1,1,1,1,2,2,2,2]) # 인덱스 번호를 부르면 해당하는 원소가 나온다.
a[idx2]

array([11, 11, 11, 11, 22, 22, 22, 22, 33, 33, 33, 33])

## 다차원 배열애서의 배열 인덱싱

In [ ]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
a.shape # 행열 개수 출력

(3, 4)

In [ ]:
a[:,[True,False,True,False]] #행은 전부 출력, 열은 true만 출력(홀수만 출력됨)

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])

In [ ]:
a[[2,0,1],:] # 행의 순서를 바뀌서 출력할 수 있다.

array([[ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

## 🐉 연습문제3
```
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
             11, 12, 13, 14, 15, 16, 17, 18, 19, 20])
```
1. 3의 배수 찾기
1. 4로 나누면 1이 남는 수 찾기
1. 4로 나누면 나누어지고 3으로 나누면 1이 남는 수 찾기

In [ ]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
             11, 12, 13, 14, 15, 16, 17, 18, 19, 20])


In [ ]:
x[x%3==0] # x%3의 결과가 참인 경우만 출력함

array([ 3,  6,  9, 12, 15, 18])

In [ ]:
x[x%4==0]

array([ 4,  8, 12, 16, 20])

In [ ]:
x[(x%4==0)&(x%3==1)] # 여러개를 조건으로  넣을 수 있고, 두 조건이 참일때만 결과를 출력함

array([ 4, 16])

## 배열 검색

In [ ]:
arr = np.array([1,2,3,4,5,4,4])

In [ ]:
x =np.where(arr == 4) # np.where(condititon) -> 조건을 만족시키는 인덱스를 리턴, (배열명 == 원하는 조건)
x

(array([3, 5, 6]),)

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr % 2 == 0)

x # 결과가 인덱스로 나옴! 헷갈림 주의

(array([1, 3, 5, 7]),)

In [ ]:
arr[x] # 조건을 통해서 뽑은 인덱스를 넣어서 원소로 결과를 볼 수 있다.

array([2, 4, 6, 8])